### ISSUE TITLE
warning: unknown feature specified for `-Ctarget-feature`: `long-calls`

### ISSUE THREAD

**Issue by boozook** [dcoles/flipperzero-hello-rust#2]
rustc 1.66.0-nightly (432abd86f 2022-09-20)
Apple clang version 13.1.6 (clang-1316.0.21.2.5)

**Comment by dcoles** [comment]
Hi @boozook,

Thanks for the report. Despite the warning, yes, this flag is actually passed to the LLVM `arm`  backend (you can see all the target feature flags with `rustc --target thumbv7em-none-eabihf -C target-feature=help`).

Originally this flag was added because the Flipper Zero loader could not relocate external symbols when they were generated by LLVM, though it seems this might have been fixed by the new loader (see flipperdevices/flipperzero-firmware#1744).

I'll do some testing and see if it can now be removed from `RUSTFLAGS`.

**Comment by dcoles** [comment]
Fixed in a554e8c1ad9e9baa1adf6b576515a0350884cde3.
